"""
Generates crontab entries from data/schedule.json and installs them.
Each entry hits the zipper /wake endpoint at the scheduled time.

Usage: python setup_cron.py
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SCHEDULE_PATH = ROOT / "data" / "schedule.json"
ZIPPER_URL = "http://localhost:4199"
LOG = ROOT / "logs" / "cron.log"


def load_schedule() -> dict:
    if not SCHEDULE_PATH.exists():
        print(f"[setup] no schedule file found at {SCHEDULE_PATH}")
        return {"daily": []}
    return json.loads(SCHEDULE_PATH.read_text())


def generate_entries(daily_times: list[str]) -> list[str]:
    entries = []
    for slot in daily_times:
        h, m = map(int, slot.split(":"))
        cmd = f'curl -s -X POST {ZIPPER_URL}/wake -H "Content-Type: application/json" -d \'{{"time":"{slot}"}}\' >> {LOG} 2>&1'
        entries.append(f"{m} {h} * * * {cmd}")
    return entries


def install_crontab(new_entries: list[str]):
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = result.stdout if result.returncode == 0 else ""
    lines = [l for l in existing.splitlines() if "zipper/wake" not in l]

    lines.append("")
    lines.append("# zipper schedule (auto-generated by setup_cron.py)")
    lines.extend(new_entries)
    lines.append("")

    new_crontab = "\n".join(lines) + "\n"
    proc = subprocess.run(["crontab", "-"], input=new_crontab, text=True, capture_output=True)
    if proc.returncode != 0:
        print(f"[setup] error: {proc.stderr}")
        sys.exit(1)


def main():
    schedule = load_schedule()
    daily = schedule.get("daily", [])

    if not daily:
        print("[setup] no daily times in schedule — nothing to install")
        return

    entries = generate_entries(daily)
    LOG.parent.mkdir(parents=True, exist_ok=True)

    print(f"[setup] installing {len(entries)} cron entries:")
    for e in entries:
        print(f"  {e}")

    install_crontab(entries)
    print("[setup] done — zipper server must be running for cron to work")


if __name__ == "__main__":
    main()
