"""zipper.status

The generated snapshot in Meta/Status.md.
"""
import os, glob

from .core import *          # noqa: F401,F403 -- the shared vocabulary
from . import core


def cmd_status(a):
    os.makedirs(METADIR, exist_ok=True)
    notes = []
    for p in iter_notes():
        pairs, _ = read_note(p)
        notes.append((p, fm_dict(pairs)))

    L = ['---', 'tags: [meta, view]', 'type: view', 'view_kind: generated',
         'status: living', 'source: zipper status',
         'generated: ' + core.TODAY.isoformat(), '---', '',
         '# Status', '',
         '*Generated by `zipper status` on %s. Do not hand-edit — rerun instead.*'
         % core.TODAY.isoformat(), '']

    from .views import next_tasks
    by = next_tasks()
    first = lambda p: (by.get(title_of(p)) or [{'text': '**none**'}])[0]['text']

    # revenue scoreboard
    rev = [(p, d) for p, d in notes if d.get('revenue_intent') == 'true']
    rev.sort(key=lambda x: -float(x[1].get('revenue_to_date', 0) or 0))
    L += ['## The scoreboard', '',
          '| Venture | Stage | $ to date | Customers | Next task |',
          '|---|---|---|---|---|']
    total = 0.0
    for p, d in rev:
        total += float(d.get('revenue_to_date', 0) or 0)
        cust = d.get('paying_users', d.get('customers', '—'))
        L.append('| [[%s]] | %s | %s | %s | %s |' %
                 (title_of(p), d.get('stage', '—'), d.get('revenue_to_date', '—'),
                  cust, first(p)))
    L += ['', '**%d ventures, $%g total.**' % (len(rev), total), '']

    # drifting
    drift = [(p, d) for p, d in notes
             if d.get('status') == 'active' and d.get('type') == 'project'
             and not by.get(title_of(p))]
    L += ['## Drifting — active project, no open task', '']
    L += ['- [[%s]] (%s)' % (title_of(p), d.get('type', '?')) for p, d in drift] or ['- none']
    L += ['']

    # stale
    stale = []
    for p, d in notes:
        if d.get('status') == 'active' and d.get('note_updated'):
            n = _days_since(d['note_updated'])
            if n is not None and n > 30:
                stale.append((n, p, d))
    stale.sort(reverse=True)
    L += ['', '## Stale — says active, note untouched 30+ days', '']
    L += ['- [[%s]] — %d days (last_touched: %s)' %
          (title_of(p), n, d.get('last_touched', '—')) for n, p, d in stale] or ['- none']
    L += ['']

    # reviews
    # Decisions/ is not in SKIP_DIRS, so notes already covers it. A second
    # explicit pass over DECDIR listed every decision twice.
    due = [(d['review'], p, d) for p, d in notes if d.get('review')]
    due.sort()
    L += ['', '## Reviews', '']
    for when, p, d in due:
        flag = ' ⟵ **due**' if when <= core.TODAY.isoformat() else ''
        L.append('- `%s` [[%s]]%s' % (when, title_of(p), flag))
    if not due:
        L.append('- none scheduled')
    L += ['']

    # blocked / open loops
    blocked = [(p, d) for p, d in notes if d.get('blocked_by') or d.get('open_loop') == 'true']
    L += ['', '## Blocked and open loops', '']
    L += ['- [[%s]] — %s' % (title_of(p), d.get('blocked_by', 'open loop'))
          for p, d in blocked] or ['- none']
    L += ['']

    # log activity
    logs = sorted(glob.glob(os.path.join(LOGDIR, '*.md')))
    recent = [f for f in logs if _days_since(title_of(f)) is not None
              and _days_since(title_of(f)) <= 14]
    # Count the section, not just the file. LINK_RE stops at '#' because that is
    # what `sync` needs -- a mention of [[Others#Willis]] is evidence the Others
    # note was touched. But for attention it throws away the only thing worth
    # knowing: folding five people into one note turned "Willis x 4" into a share
    # of "Others x 5", and Willis carrying the thesis is exactly the signal this
    # section exists to show.
    mentioned = {}
    for f in recent:
        for link in ANCHOR_RE.findall(open(f, encoding='utf-8').read()):
            mentioned[link.strip()] = mentioned.get(link.strip(), 0) + 1
    L += ['', '## Attention, last 14 days', '',
          '%d log entr%s.' % (len(recent), 'y' if len(recent) == 1 else 'ies'), '']
    for k, v in sorted(mentioned.items(), key=lambda x: -x[1])[:15]:
        L.append('- [[%s]] × %d' % (k, v))
    if not mentioned:
        L.append('*Nothing logged. Every "what have I been working on" query is blind until this fills in.*')

    # untouched actives, cross-referenced with attention
    if recent:
        actives = set(title_of(p) for p, d in notes if d.get('status') == 'active')
        ignored = sorted(actives - set(mentioned))
        L += ['', '### Active but unmentioned in any recent log', '']
        L += ['- [[%s]]' % t for t in ignored] or ['- none']

    L += ['', 'Related: [[Dashboard]] · [[Agenda]] · [[Review]] · [[Home]]', '']
    os.makedirs(METADIR, exist_ok=True)     # a new vault has no Meta/ until now
    open(os.path.join(METADIR, 'Status.md'), 'w', encoding='utf-8').write('\n'.join(L))
    print('status -> Meta/Status.md  (%d ventures, %d drifting, %d stale, %d blocked)'
          % (len(rev), len(drift), len(stale), len(blocked)))
    return 0
