"""
Generates crontab entries from data/schedule.json and task queue.
Each entry hits the zipper /wake endpoint at the scheduled time.

Usage: python setup_cron.py
"""
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Ensure app root is on sys.path when run as a standalone script
_here = Path(__file__).resolve().parent.parent
if str(_here) not in sys.path:
    sys.path.insert(0, str(_here))

from utils.constants import ZIPPER_URL
from storage.schedule import load_schedule
from storage.tasks import list_tasks

ROOT = Path(__file__).parent.parent
LOG = ROOT / "logs" / "cron.log"


def generate_daily_entries(daily_times: list[str]) -> list[str]:
    entries = []
    for slot in daily_times:
        h, m = map(int, slot.split(":"))
        cmd = f'curl -s -X POST {ZIPPER_URL}/wake -H "Content-Type: application/json" -d \'{{"time":"{slot}"}}\' >> {LOG} 2>&1'
        entries.append(f"{m} {h} * * * {cmd}")
    return entries


def generate_oneshot_entries(oneshots: list) -> list[str]:
    entries = []
    for entry in oneshots:
        at = datetime.fromisoformat(entry["at"])
        slot = at.strftime("%H:%M")
        cmd = f'curl -s -X POST {ZIPPER_URL}/wake -H "Content-Type: application/json" -d \'{{"time":"{slot}"}}\' >> {LOG} 2>&1'
        entries.append(f"{at.minute} {at.hour} {at.day} {at.month} * {cmd}")
    return entries


def generate_task_entries(tasks: list) -> list[str]:
    """Generate cron entries for scheduled tasks from the task queue."""
    entries = []
    for task in tasks:
        if task.get("schedule") and task.get("cron_line"):
            entries.append(task["cron_line"])
    return entries


def install_crontab(new_entries: list[str]):
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = result.stdout if result.returncode == 0 else ""
    # Remove old zipper entries and comments
    in_zipper_section = False
    lines = []
    for l in existing.splitlines():
        if "# zipper schedule" in l:
            in_zipper_section = True
            continue
        if in_zipper_section and (l.startswith("#") or "/wake" in l or l.strip() == ""):
            continue
        in_zipper_section = False
        lines.append(l)

    lines.append("")
    lines.append("# zipper schedule (auto-generated by setup_cron.py)")
    lines.extend(new_entries)
    lines.append("")

    new_crontab = "\n".join(lines) + "\n"
    proc = subprocess.run(["crontab", "-"], input=new_crontab, text=True, capture_output=True)
    if proc.returncode != 0:
        print(f"[setup] error: {proc.stderr}")
        sys.exit(1)


def main():
    schedule = load_schedule()
    daily = schedule.get("daily", [])
    oneshots = schedule.get("oneshot", [])
    
    # Load scheduled tasks from queue
    tasks = list_tasks(status="pending")
    scheduled_tasks = [t for t in tasks if t.get("schedule")]

    daily_entries = generate_daily_entries(daily)
    oneshot_entries = generate_oneshot_entries(oneshots)
    task_entries = generate_task_entries(scheduled_tasks)
    entries = daily_entries + oneshot_entries + task_entries

    if not entries:
        print("[setup] no entries in schedule — nothing to install")
        return

    LOG.parent.mkdir(parents=True, exist_ok=True)

    print(f"[setup] installing {len(entries)} cron entries ({len(daily_entries)} daily, {len(oneshot_entries)} oneshot, {len(task_entries)} task-scheduled):")
    for e in entries[:20]:  # show first 20 to avoid spam
        print(f"  {e}")
    if len(entries) > 20:
        print(f"  ... and {len(entries) - 20} more")

    install_crontab(entries)
    print("[setup] done — zipper server must be running for cron to work")


if __name__ == "__main__":
    main()
